import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <header className="py-4 shadow-md">
          <div className="container">
            <Link href="/">
              <h1 className="text-xl font-bold">Task App</h1>
            </Link>
          </div>
        </header>
        <main className="container my-6">
          {children}
        </main>
      </body>
    </html>
  )
}
